# Generated by Django 5.1b1 on 2024-07-28 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News_post',
        ),
    ]
